### ISSUE TITLE
Find mp3 Path Automatically

### ISSUE THREAD

**Issue by LuckFire** [Hamy-os/computer-outro#3]
EDIT: Probably best to reference [this pull request](https://github.com/Hamy-os/computer-outro/pull/6) since I didn't know there was a better way to find the base directory path. very awesome and cool

I'm too lazy to make a pull request so I'll just describe here on what you can do, up to you if you wanna. Instead of making the user manually [change the path](https://github.com/Hamy-os/computer-outro/blob/main/main.py#L12) for the mp3, you can use some os.path functions to find where the mp3 is located.

`os.path.dirname(os.path.abspath(__file__))` will find the directory that the `index.py` file is located in. So as long as the user doesn't move the index.py file or outro.mp3 file, it'll always work.

After we have the path, we can then just open the `outro.mp3` file using an f-string. `webbrowser.open(f"{os.path.dirname(os.path.abspath(__file__))}/outro.mp3)`. Should use a variable for the file path so it looks more readable.

The way you'd implement it would be something along the lines of
```py
import os
import webbrowser

path = os.path.dirname(os.path.abspath(__file__))
webbrowser.open(f"{path}/outro.mp3")
```

**Comment by muchtek** [comment]
yeah, you can use `os.getcwd()` to get the active directory of the file, and i just joined the `outro.mp3` file to the end of that to somewhat facilitate it
